<%--
  Created by IntelliJ IDEA.
  User: bree2
  Date: 4/27/22
  Time: 8:27 PM
  To change this template use File | Settings | File Templates.
--%>
<%
    java.sql.Connection conn;                 // Connection: A connection with a specific database.
    java.sql.ResultSet rs;                   // ResultSet: A table of data representing a database result set, which is usually generated by executing a statement that queries the database.
    java.sql.Statement st;                   // Statement: The object used for executing a static SQL statement and returning the results it produces.
    // mysql database to work with your project. Go to,
    // Your project -> right click -> properties -> Libraries -> Compiler tab -> Add library -> select "MySQL JDBC Driver" library -> Ok
    Class.forName("com.mysql.jdbc.Driver"); //to connect mysql database
    conn = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/businessdirectory", "root", "BreeF#11");
    st = conn.createStatement();

    //get parameter value by using the 'name' of the field
    String uname = request.getParameter("username");
    String password = request.getParameter("password");

    String qr = "SELECT username FROM users WHERE username = '"+uname+"' and password = '"+password+"'";    //query to select if the username already exists or not
    rs = st.executeQuery(qr);
    if(rs.next())
    {
        // if username and password is correct
        session.setAttribute("uname", uname);
        response.sendRedirect("index.jsp");
    }
    else
    {
        // if username or password is incorrect
        // passing variable "c" with URL
        // lets say "c" is for "username/password is incorrect"
        response.sendRedirect("login.jsp?c");
    }
%>